### ISSUE TITLE
SRV records mishandled?

### ISSUE THREAD

**Issue by rhester72** [tssva/dnshttps-proxy#4]
I noticed in my SoHo setup that after switching to dnshttps-proxy, I could no longer VPN into work using Cisco SSL VPN.  It would seem the root cause is a difference in how SRV record queries are returned.

Sample output from unbound:

$ dig SRV _sip._tcp.cisco.com @localhost                                                                  
; <<>> DiG 9.9.5-9+deb8u8-Raspbian <<>> SRV _sip._tcp.cisco.com @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32463
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_sip._tcp.cisco.com.           IN      SRV

;; ANSWER SECTION:
_sip._tcp.cisco.com.    3463    IN      SRV     10 10 5060 vcsgw.cisco.com.

;; AUTHORITY SECTION:
_tcp.cisco.com.         86263   IN      NS      ns1.cisco.com.
_tcp.cisco.com.         86263   IN      NS      ns2.cisco.com.

;; ADDITIONAL SECTION:
ns1.cisco.com.          1663    IN      AAAA    2001:420:1101:6::a
ns2.cisco.com.          1663    IN      AAAA    2001:420:2041:5000::a
ns1.cisco.com.          463     IN      A       72.163.5.201
ns2.cisco.com.          1663    IN      A       64.102.255.44

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Wed Dec 21 17:12:55 EST 2016
;; MSG SIZE  rcvd: 207

Output of the same query using dnshttps-proxy:

$ dig -p 54 SRV _sip._tcp.cisco.com @localhost

; <<>> DiG 9.9.5-9+deb8u8-Raspbian <<>> -p 54 SRV _sip._tcp.cisco.com @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58842
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_sip._tcp.cisco.com.           IN      SRV

;; ANSWER SECTION:
_sip._tcp.cisco.com.    3496    IN      SRV     10 10 5060 vcsgw.cisco.com.

;; Query time: 302 msec
;; SERVER: ::1#54(::1)
;; WHEN: Wed Dec 21 17:12:51 EST 2016
;; MSG SIZE  rcvd: 91

Note the SRV data is indeed returned, but the 'additional' data isn't...which means that systems that depend on getting the SRV and A/AAAA data in one shot are going to fail hard.

**Comment by tssva** [comment]
I ran the same query against the Google Public DNS servers, OpenDNS and Level3's public DNS. All 3 return the same result dnshttps-proxy returns. Since dnshttps-proxy depends on what Google Public DNS returns there isn't much that can be done. I suggest adding this domain to your bypass list.

```
dig SRV _sip._tcp.cisco.com @8.8.8.8
; <<>> DiG 9.8.3-P1 <<>> SRV _sip._tcp.cisco.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51101
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_sip._tcp.cisco.com.		IN	SRV

;; ANSWER SECTION:
_sip._tcp.cisco.com.	2655	IN	SRV	10 10 5060 vcsgw.cisco.com.

;; Query time: 55 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Dec 21 17:29:54 2016
;; MSG SIZE  rcvd: 72

dig SRV _sip._tcp.cisco.com @208.67.220.220
; <<>> DiG 9.8.3-P1 <<>> SRV _sip._tcp.cisco.com @208.67.220.220
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7881
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_sip._tcp.cisco.com.		IN	SRV

;; ANSWER SECTION:
_sip._tcp.cisco.com.	3600	IN	SRV	10 10 5060 vcsgw.cisco.com.

;; Query time: 62 msec
;; SERVER: 208.67.220.220#53(208.67.220.220)
;; WHEN: Wed Dec 21 17:30:57 2016
;; MSG SIZE  rcvd: 72

dig SRV _sip._tcp.cisco.com @4.2.2.1
; <<>> DiG 9.8.3-P1 <<>> SRV _sip._tcp.cisco.com @4.2.2.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28946
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_sip._tcp.cisco.com.		IN	SRV

;; ANSWER SECTION:
_sip._tcp.cisco.com.	3600	IN	SRV	10 10 5060 vcsgw.cisco.com.

;; Query time: 48 msec
;; SERVER: 4.2.2.1#53(4.2.2.1)
;; WHEN: Wed Dec 21 17:31:40 2016
;; MSG SIZE  rcvd: 72
```

**Comment by rhester72** [comment]
My apologies, you are absolutely correct.  Our CIT group's initial analysis of my VPN issue was in error - the real root cause is that the Cisco VPN client is configured for a 1-second timeout on DNS lookups, and roughly half the time the HTTPS lookup takes in excess of 1 second - if you keep trying, it will eventually work.  Lookups through direct recursion take about 200msec max and therefore always succeed (from the VPN client's perspective).

Very sorry for the confusion, no bug noted.
